#!/usr/bin/env bash

#pwd
#echo "${BASH_SOURCE[0]}"
#echo $( dirname "${BASH_SOURCE[0]}" )
#echo "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd
#SCRIPT_DIR=$( cd -- "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
#
#echo ${SCRIPT_DIR}

cd $(dirname ${0})

cp -rf ./src/* ../backend/src/main/resources/static
